// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	reflect "reflect"

	mock "github.com/stretchr/testify/mock"

	tagManager "github.com/startup-of-zero-reais/dynamo-for-lambda/tag-manager"
)

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

// GetHash provides a mock function with given fields:
func (_m *Manager) GetHash() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetMapper provides a mock function with given fields:
func (_m *Manager) GetMapper() tagManager.TagMapperInterface {
	ret := _m.Called()

	var r0 tagManager.TagMapperInterface
	if rf, ok := ret.Get(0).(func() tagManager.TagMapperInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tagManager.TagMapperInterface)
		}
	}

	return r0
}

// GetRange provides a mock function with given fields:
func (_m *Manager) GetRange() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetType provides a mock function with given fields: key
func (_m *Manager) GetType(key string) reflect.Kind {
	ret := _m.Called(key)

	var r0 reflect.Kind
	if rf, ok := ret.Get(0).(func(string) reflect.Kind); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(reflect.Kind)
	}

	return r0
}

// MapTags provides a mock function with given fields:
func (_m *Manager) MapTags() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetEntity provides a mock function with given fields: entity
func (_m *Manager) SetEntity(entity interface{}) tagManager.Manager {
	ret := _m.Called(entity)

	var r0 tagManager.Manager
	if rf, ok := ret.Get(0).(func(interface{}) tagManager.Manager); ok {
		r0 = rf(entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tagManager.Manager)
		}
	}

	return r0
}
