// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	tagManager "github.com/startup-of-zero-reais/dynamo-for-lambda/tag-manager"
	mock "github.com/stretchr/testify/mock"
)

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

// MapTags provides a mock function with given fields:
func (_m *Manager) MapTags() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetEntity provides a mock function with given fields: entity
func (_m *Manager) SetEntity(entity interface{}) tagManager.Manager {
	ret := _m.Called(entity)

	var r0 tagManager.Manager
	if rf, ok := ret.Get(0).(func(interface{}) tagManager.Manager); ok {
		r0 = rf(entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tagManager.Manager)
		}
	}

	return r0
}
