// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	reflect "reflect"

	mock "github.com/stretchr/testify/mock"
)

// TagGetters is an autogenerated mock type for the TagGetters type
type TagGetters struct {
	mock.Mock
}

// GetHash provides a mock function with given fields:
func (_m *TagGetters) GetHash() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetRange provides a mock function with given fields:
func (_m *TagGetters) GetRange() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetType provides a mock function with given fields: key
func (_m *TagGetters) GetType(key string) reflect.Kind {
	ret := _m.Called(key)

	var r0 reflect.Kind
	if rf, ok := ret.Get(0).(func(string) reflect.Kind); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(reflect.Kind)
	}

	return r0
}
