// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	reflect "reflect"

	mock "github.com/stretchr/testify/mock"
)

// TagHandler is an autogenerated mock type for the TagHandler type
type TagHandler struct {
	mock.Mock
}

// Execute provides a mock function with given fields: tagsPair, field
func (_m *TagHandler) Execute(tagsPair []string, field reflect.StructField) error {
	ret := _m.Called(tagsPair, field)

	var r0 error
	if rf, ok := ret.Get(0).(func([]string, reflect.StructField) error); ok {
		r0 = rf(tagsPair, field)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
