// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Log is an autogenerated mock type for the Log type
type Log struct {
	mock.Mock
}

// Critical provides a mock function with given fields: s, v
func (_m *Log) Critical(s string, v ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, s)
	_ca = append(_ca, v...)
	_m.Called(_ca...)
}

// Debug provides a mock function with given fields: s, v
func (_m *Log) Debug(s string, v ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, s)
	_ca = append(_ca, v...)
	_m.Called(_ca...)
}

// Error provides a mock function with given fields: s, v
func (_m *Log) Error(s string, v ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, s)
	_ca = append(_ca, v...)
	_m.Called(_ca...)
}

// Info provides a mock function with given fields: s, v
func (_m *Log) Info(s string, v ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, s)
	_ca = append(_ca, v...)
	_m.Called(_ca...)
}

// Warn provides a mock function with given fields: s, v
func (_m *Log) Warn(s string, v ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, s)
	_ca = append(_ca, v...)
	_m.Called(_ca...)
}

// printer provides a mock function with given fields: s, v
func (_m *Log) printer(s string, v ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, s)
	_ca = append(_ca, v...)
	_m.Called(_ca...)
}
